geekshop/admins/urls.py
from django.urls import path

from admins.views import UserCreateView, UserUpdateView, UserDeleteView, \
    UserListView, ProductCategoriesListView, ProductCategoriesCreateView, \
    ProductCategoriesUpdateView, ProductCategoriesDeleteView, ProductsListView, ProductsCreateView, \
    ProductsUpdateView, ProductsDeleteView, IndexTemplateView

app_name = 'admins'


urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('users/', UserListView.as_view(), name='admin_users'),
    path('users-create/', UserCreateView.as_view(), name='admin_users_create'),
    path('users-update/<int:pk>', UserUpdateView.as_view(), name='admin_users_update'),
    path('users-delete/<int:pk>', UserDeleteView.as_view(), name='admin_users_delete'),
    path('product-categories/', ProductCategoriesListView.as_view(), name='admin_product_categories'),
    path('product-categories-create/', ProductCategoriesCreateView.as_view(), name='admin_product_categories_create'),
    path('product-categories-update/<int:pk>', ProductCategoriesUpdateView.as_view(), name='admin_product_categories_update'),
    path('product-categories-delete/<int:pk>', ProductCategoriesDeleteView.as_view(), name='admin_product_categories_delete'),
    path('products/', ProductsListView.as_view(), name='admin_products'),
    path('products-create/', ProductsCreateView.as_view(), name='admin_products_create'),
    path('products-update/<int:pk>', ProductsUpdateView.as_view(), name='admin_products_update'),
    path('products-delete/<int:pk>', ProductsDeleteView.as_view(), name='admin_products_delete'),
]

geekshop/geekshop/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('orders/', include('ordersapp.urls', namespace='orders')),

    path('i18n/', include('django.conf.urls.i18n')),

    path('', include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('debug/', include(debug_toolbar.urls))]

geekshop/admins/templates/admins/includes/siberia_bar.html
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Приложения</div>
                    <a class="nav-link" href="{% url 'admins:admin_users' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        Пользователи
                    </a>
                    <a class="nav-link" href="{% url 'admins:admin_product_categories' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-shopping-basket"></i>
                        </div>
                        Категории
                    </a>
                    <a class="nav-link" href="{% url 'admins:admin_products' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-tshirt"></i>
                        </div>
                        Продукты
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
    </div>