geekshop/admins/urls.py
from django.urls import path

from admins.views import UserCreateView, UserUpdateView, UserDeleteView, \
    UserListView, ProductCategoriesListView, ProductCategoriesCreateView, \
    ProductCategoriesUpdateView, ProductCategoriesDeleteView, ProductsListView, ProductsCreateView, \
    ProductsUpdateView, ProductsDeleteView, IndexTemplateView

app_name = 'admins'


urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('users/', UserListView.as_view(), name='admin_users'),
    path('users-create/', UserCreateView.as_view(), name='admin_users_create'),
    path('users-update/<int:pk>', UserUpdateView.as_view(), name='admin_users_update'),
    path('users-delete/<int:pk>', UserDeleteView.as_view(), name='admin_users_delete'),
    path('product-categories/', ProductCategoriesListView.as_view(), name='admin_product_categories'),
    path('product-categories-create/', ProductCategoriesCreateView.as_view(), name='admin_product_categories_create'),
    path('product-categories-update/<int:pk>', ProductCategoriesUpdateView.as_view(), name='admin_product_categories_update'),
    path('product-categories-delete/<int:pk>', ProductCategoriesDeleteView.as_view(), name='admin_product_categories_delete'),
    path('products/', ProductsListView.as_view(), name='admin_products'),
    path('products-create/', ProductsCreateView.as_view(), name='admin_products_create'),
    path('products-update/<int:pk>', ProductsUpdateView.as_view(), name='admin_products_update'),
    path('products-delete/<int:pk>', ProductsDeleteView.as_view(), name='admin_products_delete'),
]

geekshop/authapp/urls.py
from django.urls import path
from authapp.views import UserLoginView, UserRegisterView, UserProfileView, UserLogoutView

app_name = 'authapp'
urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('logout/', UserLogoutView.as_view(), name='logout'),

    path('verify/<str:email>/<str:activate_key>', UserRegisterView.verify, name='verify'),
]

geekshop/geekshop/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='mainapp')),
    path('users/', include('authapp.urls', namespace='authapp')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('orders/', include('ordersapp.urls', namespace='orders')),

    path('i18n/', include('django.conf.urls.i18n')),

    path('', include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('debug/', include(debug_toolbar.urls))]

geekshop/admins/templates/admins/admin-product-categories-create.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Создание категории</h1>
                <form action="{% url 'admins:admin_product_categories_create' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                {{ form.name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12">
                            <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                            {{ form.description }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-product-categories-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Категории</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Категории
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Ид.</th>
                                    <th>Название</th>
                                    <th>Описание</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Ид.</th>
                                    <th>Название</th>
                                    <th>Описание</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for category in object_list %}
                                    <tr>
                                        <td><a href="{% url 'admins:admin_product_categories_update' category.id  %}" style="color: dodgerblue">{{ category.id }}</a></td>
                                        <td>{{ category.name }}</td>
                                        <td>{{ category.description }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_product_categories_create' %}">
                            <button class="btn btn-success">Создать категорию</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-product-categories-update-delete.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование категории | {{ productcategory.id }}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admin_product_categories_update' productcategory.id  %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                    {{ form.name }}
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-lg-12">
                                <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                                {{ form.description }}
                            </div>
                        </div>
                        <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <form action="{% url 'admins:admin_product_categories_delete' productcategory.id %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </div>
                    </div>
                </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-products-create.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Создание продукта</h1>
                <form action="{% url 'admins:admin_products_create' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена в руб.</label>
                                {{ form.price }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество</label>
                            {{ form.quantity }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                            {{ form.category }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12">
                            <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                            {{ form.description }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-products-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Продукты</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Продукты
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Ид.</th>
                                    <th>Название</th>
                                    <th>Описание</th>
                                    <th>Цена</th>
                                    <th>Количество</th>
                                    <th>Категория</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Ид.</th>
                                    <th>Название</th>
                                    <th>Описание</th>
                                    <th>Цена</th>
                                    <th>Количество</th>
                                    <th>Категория</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for product in object_list %}
                                    <tr>
                                        <td><a href="{% url 'admins:admin_products_update' product.id %}" style="color: dodgerblue">{{ product.id }}</a></td>
                                        <td>{{ product.name }}</td>
                                        <td>{{ product.description }}</td>
                                        <td>{{ product.price }}</td>
                                        <td>{{ product.quantity }}</td>
                                        <td>{{ product.category }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_products_create' %}">
                            <button class="btn btn-success">Создать продукт</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-products-update-delete.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование продукта | {{ product.name }}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admin_products_update' product.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена в руб.</label>
                                {{ form.price }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.quantity.id_for_label }}">Количество</label>
                            {{ form.quantity }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                            {{ form.category }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                            {{ form.description }}
                        </div>
                        <div class="col-lg-6">
                            <img width="430" height="100" style="margin-top: 28px"
                                 src=" {{ product.image.url }} " class="img-thumbnail">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <form action="{% url 'admins:admin_products_delete' product.id %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </div>
                    </div>
                </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-users-create.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Создание пользователя</h1>
                <form action="{% url 'admins:admin_users_create' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-5">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-5">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                        <div class="col-lg-2">
                            <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                            {{ form.age }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                            {{ form.password1 }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.password2.id_for_label }}">Повторите пароль</label>
                            {{ form.password2 }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-users-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Пользователи</h1>
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table mr-1"></i>
                        Пользователи
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Имя пользователя</th>
                                    <th>Имя</th>
                                    <th>Фамилия</th>
                                    <th>Адрес эл. почты</th>
                                    <th>Персонал сайта</th>
                                    <th>Активный</th>
                                </tr>
                                </thead>
                                <tfoot>
                                <tr>
                                    <th>Имя пользователя</th>
                                    <th>Имя</th>
                                    <th>Фамилия</th>
                                    <th>Адрес эл. почты</th>
                                    <th>Персонал сайта</th>
                                    <th>Активный</th>
                                </tr>
                                </tfoot>
                                <tbody>
                                {% for user in object_list %}
                                    <tr>
                                        <td><a href="{% url 'admins:admin_users_update' user.id %}" style="color: dodgerblue">{{ user.username }}</a></td>
                                        <td>{{ user.first_name }}</td>
                                        <td>{{ user.last_name }}</td>
                                        <td>{{ user.email }}</td>
                                        <td class="text-center">
                                            {% if user.is_staff %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}
                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                        <td class="text-center">
                                            {% if user.is_active %}
                                                <i class="fas fa-check-circle"></i>
                                            {% else %}
                                                <i class="fas fa-times-circle"></i>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'admins:admin_users_create' %}">
                            <button class="btn btn-success">Создать пользователя</button>
                        </a>
                    </div>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}

geekshop/admins/templates/admins/admin-users-update-delete.html
{% extends 'admins/base.html' %}

{% block content %}
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
                <div class="card-body">
                    <form action="{% url 'admins:admin_users_update' user.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-5">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-5">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                        <div class="col-lg-2">
                            <label class="small mb-1" for="{{ form.age.id_for_label }}">Возраст</label>
                            {{ form.age }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                            {{ form.password1 }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.password2.id_for_label }}">Повторите пароль</label>
                            {{ form.password2 }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <form action="{% url 'admins:admin_users_delete' user.id %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                        </div>
                    </div>
                </form>
                </div>
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2021</div>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}